apps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path("verify/", views.VerifyRegisterCodeView.as_view(), name="verify"),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutUserView.as_view(), name="logout"),
    path("userpanel/", views.UserPanelView.as_view(), name="userpanel"),
    path("show_last_orders/", views.show_last_orders, name="show_last_orders"),   
    path("show_user_payments/", views.show_user_payments, name="show_user_payments"),   
    path("remember_password/", views.RememberPasswordView.as_view(), name="remember_password"),
    path("change_password/<token>/", views.ChangePasswordView.as_view(), name="change_password"),
    path("update_profile/", views.UpdateProfileView.as_view(), name="update_profile"),    
    path("newsletter/", views.SubscribeToNewsletterView.as_view(), name="newsletter"),  
]

supermarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main'), name='main'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts'), name='accounts'),
    path('products/', include('apps.products.urls', namespace='products'), name='products'),
    path('orders/', include('apps.orders.urls', namespace='orders'), name='orders'),
    path('discount/', include('apps.discount.urls', namespace='discount'), name='discount'),
    path('payments/', include('apps.payments.urls', namespace='payments'), name='payments'),
    path('comments/', include('apps.comments.urls', namespace='comments'), name='comments'),
    path('warehauses/', include('apps.warehauses.urls', namespace='warehauses'), name='warehauses'),
    path('scoring_favorite/', include('apps.scoring_favorite.urls', namespace='scoring_favorite'), name='scoring_favorite'),
    path('search/', include('apps.search.urls', namespace='search'), name='search'),
    path('blog/', include('apps.blog.urls', namespace='blog'), name='blog'),
    path('ckeditor',include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
admin.site.site_header = "پنل مدیریت"
#admin.site.index_title = ""  scoring_faivorit

handler404 = "apps.main.views.handler404"

templates/accounts_app/change_password.html
{% extends 'main_template.html' %}

{% block title %}تغییر رمز عبور{%endblock title %}

{% block content %}

<section class="checkout spad" style="text-align: center;" dir="rtl">
    <div class="container">
        <div class="checkout__form"  style="text-align: right;">
            <h4>تغییر گذرواژه</h4>
            <form action="" method="post">
                <div class="row">
                    <div class="col-lg-8 col-md-6" >
                        <div class="row">
                            <div class="col-lg-6" style="margin:auto;">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="site-btn">ثبت</button>
                            </div>      
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

templates/accounts_app/login.html
{% extends 'main_template.html' %}

{% block title %}ورود{%endblock title %}

{% block content %}

<section class="checkout spad" style="text-align: center;" dir="rtl">
    <div class="container">
        <div class="checkout__form"  style="text-align: right;">
            <h4>ورود</h4>
            <form action="" method="post">
                <div class="row">
                    <div class="col-lg-8 col-md-6" >
                        <div class="row">
                            <div class="col-lg-6" style="margin:auto;">
                                {% csrf_token %}
                                {{form.as_p}}
                                <p>ساخت <a href="{% url 'accounts:register' %}" style="color:blue">حساب کاربری جدید</a></p>
                                <p><a href="{% url 'accounts:remember_password' %}" style="color:blue">فراموشی گذرواژه</a></p>
                                <button type="submit" class="site-btn">ورود</button>
                            </div>      
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

templates/accounts_app/register.html
{% extends 'main_template.html' %}

{% block title %}ثبت نام {%endblock title %}

{% block content %}

<section class="checkout spad" style="text-align: center;" dir="rtl">
    <div class="container">
        <div class="checkout__form"  style="text-align: right;">
            <h4>ثبت نام</h4>
            <form action="" method="post">
                <div class="row">
                    <div class="col-lg-8 col-md-6" >
                        <div class="row">
                            <div class="col-lg-6" style="margin:auto;">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="site-btn">ثبت نام</button>
                            </div>      
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

templates/accounts_app/remember_password.html
{% extends 'main_template.html' %}

{% block title %}بازیابی رمز عبور{%endblock title %}

{% block content %}

<section class="checkout spad" style="text-align: center;" dir="rtl">
    <div class="container">
        <div class="checkout__form"  style="text-align: right;">
            <h4>بازیابی گذرواژه</h4>
            <form action="" method="post">
                <div class="row">
                    <div class="col-lg-8 col-md-6" >
                        <div class="row">
                            <div class="col-lg-6" style="margin:auto;">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="site-btn">ارسال</button>
                            </div>      
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

templates/accounts_app/update_profile.html
{% extends 'user_panel-template.html' %}
{% block title %}ویرایش پروفایل{% endblock title %}

{% block content %}
<div class="block">
    <div class="container">
        <div class="row">
            {% comment %} <div class="col-12 col-lg-3 d-flex">
                <div class="account-nav flex-grow-1">
                    <h4 class="account-nav__title">ناوبری</h4>
                    <ul>
                        <li class="account-nav__item account-nav__item--active"><a href="user-dashboard.html">داشبورد</a></li>
                        <li class="account-nav__item"><a href="user-profile.html">ویرایش پروفایل</a></li>
                        <li class="account-nav__item"><a href="orders-records.html">سابقه خرید</a></li>
                        <li class="account-nav__item"><a href="change-password.html">تغییر رمز عبور</a></li>
                        <li class="account-nav__item"><a href="../index.html">خروج</a></li>
                    </ul>
                </div>
            </div> {% endcomment %}
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h5>ویرایش پروفایل</h5></div>
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{form.as_p}}
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary mt-4">ویرایش</button>
                                    <a type="button" class="btn btn-primary mt-4" href="{% url 'accounts:userpanel' %}">انصراف</a>                                    
                                </div>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts_app/user_panel.html
{% extends 'user_panel-template.html' %}
{% load render_partial %}
{% block title %}پنل کاربری{% endblock title %}

{% block content %}
    <div class= "dashboard">
        {% include "accounts_app/partials/user_info.html" %}
        {% render_partial "accounts:show_last_orders" %}
    </div>
{% endblock content %}

templates/accounts_app/verify_register_code.html
{% extends 'main_template.html' %}

{% block title %}تایید آدرس ایمیل {% endblock title %}

{% block content %}

<div class="page-header__title d-flex justify-content-center" style="padding: 100px; margin-bottom:50px">
    <h3> تایید آدرس ایمیل</h3>
</div>
<div class="block" style="padding: 10px; margin-bottom:10px">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div class="card flex-grow-1 mb-md-0">
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-group" dir="rtl">
                                {{form.as_p}}
                            </div>
                            <button type="submit" class="site-btn btn"> تایید</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}