apps/products/urls.py
from django.urls import path
from . import views

app_name="products"
urlpatterns = [
    path("categories/", views.get_products_groups, name="categories"),
    path("cheapest_products/", views.get_cheapest_products, name="cheapest_products"),
    path("latest_products/", views.get_latest_products, name="latest_products"),
    path("favorites_products/", views.get_favorites_products, name="favorites_products"),
    path("product_deatails/<slug:slug>/", views.ProductDeatailsView.as_view(), name="product_deatails"),
    path("related_products/<slug:slug>/", views.get_related_products, name="related_products"),
    path("products_groups/", views.ProductsGroupsView.as_view(), name="products_groups"),
    path("all_products/<slug:slug>/", views.ProductsView.as_view(), name="all_products"),
    path("brands_filter/<slug:slug>/", views.get_brands,name="brands_filter"),
    path("feature_filter/<slug:slug>/", views.get_feature_for_filter,name="feature_filter"),
    path("add_to_compare_list/", views.add_to_compare_list, name="add_to_compare_list"),
    path("delete_from_compare_list/", views.delete_from_compare_list, name="delete_from_compare_listt"),
    path("status_compare_list/", views.status_compare_list, name="status_compare_list"),
 

    path("ajax_admin/", views.filter_feature_value, name="filter_feature_value"),
   

]

supermarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main'), name='main'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts'), name='accounts'),
    path('products/', include('apps.products.urls', namespace='products'), name='products'),
    path('orders/', include('apps.orders.urls', namespace='orders'), name='orders'),
    path('discount/', include('apps.discount.urls', namespace='discount'), name='discount'),
    path('payments/', include('apps.payments.urls', namespace='payments'), name='payments'),
    path('comments/', include('apps.comments.urls', namespace='comments'), name='comments'),
    path('warehauses/', include('apps.warehauses.urls', namespace='warehauses'), name='warehauses'),
    path('scoring_favorite/', include('apps.scoring_favorite.urls', namespace='scoring_favorite'), name='scoring_favorite'),
    path('search/', include('apps.search.urls', namespace='search'), name='search'),
    path('blog/', include('apps.blog.urls', namespace='blog'), name='blog'),
    path('ckeditor',include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
admin.site.site_header = "پنل مدیریت"
#admin.site.index_title = ""  scoring_faivorit

handler404 = "apps.main.views.handler404"

templates/products_app/partials/brand_filter.html
<div class="sidebar__item" id="brand_container">
    <h4>برند کالا</h4>
    {% for brand in brands %}
        <label class="custom-control custom-checkbox">
            <input type="checkbox" id="brand_{{brand.id}}" name="brand" value="{{brand.id}}" class="custom-control-input" >
            <span class="custom-control-indicator"></span>
            <span class="custom-control-description">{{brand.brand_name}}</span>               
        </label>
    {% endfor %}
</div>

templates/products_app/partials/categories.html
<section class="categories">
    <div class="container">
        <div class="row">
            <div class="categories__slider owl-carousel">
                {% for product_group  in products_groups %}
                <div class="col-lg-3">    
                    <div class="categories__item set-bg" data-setbg="{{media_url}}{{product_group.image_name}}">
                        <h5><a href="{% url 'products:all_products' slug=product_group.slug %}">{{product_group.group_name}}</a></h5>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

templates/products_app/partials/cheapest_products.html
{% load humanize %}
<section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>ارزانترین محصولات</h2>
                </div>
                <div class="featured__controls">
                    <ul>
                        <a href="{% url 'products:products_groups' %}">
                        <li class="active" data-filter="*"> همه محصولات</li>
                        </a>&nbsp;&nbsp;
                        {% for product in products|slice:":4"  %}
                        <a href="{{product.get_absolute_url}}">
                        <li >{{product.product_name}}</li>&nbsp;&nbsp;&nbsp;
                        </a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row featured__filter">
            {% for product in products %}
            <div class="col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="{{media_url}}{{product.product_image}}">
                        {% if product.get_number_in_warehause > 0 %}
                        <ul class="featured__item__pic__hover">
                            <li><a onclick="addToFavorite({{product.id}})" ><i class="fa fa-heart"></i></a></li>
                            <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                            <li><a style="cursor:pointer"  onclick="add_to_shop_cart({{product.id}}, 1)"><i class="fa fa-shopping-cart"></i></a></li>
                        </ul>
                        {% endif %}
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="{{product.get_absolute_url}}">{{product.product_name}}</a></h6>
                        {% if product.get_number_in_warehause <= 0 %}
                        <span style="color:red"><b>ناموجود</b></span>
                        {% else %}
                            {% if product.price > product.get_discounted_price %}   
                                <h5><del>{{product.price|intcomma}} تومان</del></h5>
                                <h5 style="color:red">{{product.get_discounted_price}} تومان</h5>
                            {% else %}
                                <h5 >{{product.price|intcomma}} تومان</h5>
                            {% endif %}
                        {% endif %}    
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/products_app/partials/compare_table.html
{% if products %}
    <div class="container">
        <h3 style="text-align:center; color:red">کالاهای انتخابی برای مقایسه</h3>
        <table class="table table-bordered">
            <tr style="background:#f1f1f1; text-align:center;">
                <th>ویژگی کالا/کالا</th>
                {% for product in products in  %}
                <th>
                    <i class="fa fa-times product-remove"  onclick="deleteFromCompareList({{product.id}})"></i>
                    {{product.product_name}}
                </th>
                {% endfor %}
            </tr>
            {% for feature in features %}
                <tr>
                    <td style="font-size:1.2rem; font-weight:900; width:25%">
                        {{feature}}
                    </td>
                    {% for product in products %}
                        <td style="text-align:center;">
                            {% for item in product.features_of_product.all  %}
                                {% if item.feature == feature %}
                                    <span style="margin:5px">{{item.filter_value.value_title}}</span>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% else %}
    <div class="container">
        <h2 style="text-align:center; color:red; padding:100px">کالایی برای مقایسه وجود ندارد</h2>
    </div>
{% endif %}

templates/products_app/partials/favorites_products.html
{% include "partials/products/product_box.html" with type=2 %}

templates/products_app/partials/feature_filter.html
<div class="myaccordion">
<div class="accordion">
    <h4>ویژگی ها</h4>
    {% for key,value in feature_dict.items %}
    {% if value %}
        <!-- span to target fix closing accordion -->
        <span class="target-fix" id="accordion"></span>
            
        <!-- First Accoridon Option -->
        <div>
            <!-- span to target fix accordion -->
            <span class="target-fix" id="accordion{{key.id}}"></span>
            
            <!-- Link to open accordion, hidden when open --> 
            <a href="#accordion{{key.id}}" id="open-accordion1" title="open">{{key}}</a>
            
            <!-- Link to close accordion, hidden when closed -->
            <a href="#accordion" id="close-accordion1" title="close">{{key}}</a> 
            
            <!-- Accorion content goes in this div -->
            <div class="accordion-content">
                {% for item in value %}
                <label style="display:block">
                    <span>                      
                        <input id="item_{{item.id}}" name="feature" value="{{item.id}}" type="checkbox">                   
                    <span >{{item.value_title}}</span>
                </label>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        {% endfor %}
</div>
</div>

templates/products_app/partials/latest_products.html
{% include "partials/products/product_box.html" with type=1 %}

templates/products_app/partials/related_products.html
{% for product in related_products %}
    <div class="product__item">
        <div class="product__item__pic set-bg" data-setbg="{{media_url}}{{product.product_image}}">
            <ul class="product__item__pic__hover">
                <li><a href="#"><i class="fa fa-heart"></i></a></li>
                <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                <li><a href="#" onclicke="add_to_shop_cart({{product.id}}, 1)"><i class="fa fa-shopping-cart"></i></a></li>
            </ul>
        </div>
        <div class="product__item__text">
            <h6><a href="{{product.get_absolute_url}}">{{product.product_name}}</a></h6>
            <h5>{{product.price}} تومان</h5>
        </div>
    </div>
{% endfor %}