apps/orders/urls.py
from django.urls import path
from . import views
app_name = "orders"
urlpatterns = [
    path("shop_cart/", views.ShopCartView.as_view(), name="shop_cart"),
    path("show_shop_cart/", views.show_shop_cart, name="show_shop_cart"),
    path("add_to_shop_cart/", views.add_to_shop_cart, name="add_to_shop_cart"),
    path("delete_from_shop_cart/", views.delete_from_shop_cart, name="delete_from_shop_cart"),
    path("update_shop_cart/",views.update_shop_cart, name="update_shop_cart" ),
    path("status_of_shop_cart/",views.status_of_shop_cart, name="status_of_shop_cart" ),
    path("create_order/", views.CreateOrderView.as_view(), name="create_order"),
    path("checkout_order/<int:order_id>/" , views.CheckoutOrderView.as_view(), name="checkout_order"),
    path("apply_coupon/<int:order_id>/" , views.ApplyCouponView.as_view(), name="apply_coupon"),
]

supermarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls', namespace='main'), name='main'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts'), name='accounts'),
    path('products/', include('apps.products.urls', namespace='products'), name='products'),
    path('orders/', include('apps.orders.urls', namespace='orders'), name='orders'),
    path('discount/', include('apps.discount.urls', namespace='discount'), name='discount'),
    path('payments/', include('apps.payments.urls', namespace='payments'), name='payments'),
    path('comments/', include('apps.comments.urls', namespace='comments'), name='comments'),
    path('warehauses/', include('apps.warehauses.urls', namespace='warehauses'), name='warehauses'),
    path('scoring_favorite/', include('apps.scoring_favorite.urls', namespace='scoring_favorite'), name='scoring_favorite'),
    path('search/', include('apps.search.urls', namespace='search'), name='search'),
    path('blog/', include('apps.blog.urls', namespace='blog'), name='blog'),
    path('ckeditor',include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
admin.site.site_header = "پنل مدیریت"
#admin.site.index_title = ""  scoring_faivorit

handler404 = "apps.main.views.handler404"

templates/orders_app/checkout.html
{% extends 'main_template.html' %} 
{% load render_partial %}

{% block title %}فاکتور سفارش{% endblock title %}

{% block content %}
<section class="checkout spad">
    <div class="container">
        {% comment %} <div class="row">
            <div class="col-lg-12">
                <h6><span class="icon_tag_alt"></span> Have a coupon? <a href="#">Click here</a> to enter your code
                </h6>
            </div>
        </div> {% endcomment %}
        <div class="checkout__form">
            <h4>اطلاعات شخصی</h4>
            <form action="{% url 'orders:checkout_order' order_id=order.id %}" method="post" >
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <label for="">نام</label>
                                    <p><span>*</span>{{form.name}}</p>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <label for="">نام خانوادگی</label>
                                    <p><span>*</span>{{form.family}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="checkout__input">
                            <label for="">آدرس</label>
                            <p><span>*</span>{{form.adress}}</p>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <label for="">شماره موبایل</label>
                                    <p><span>*</span>{{form.mobile_number}}</p>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <label for="">ایمیل</label>
                                    <p><span>*</span>{{form.email}}</p>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <label for="">تاریخ تولد</label>
                                    <p><span>*</span>{{form.birth_date}}</p>
                                </div>
                            </div>
                        </div>          
                        <div class="checkout__input">
                            <label for="">توضیحات</label>
                            <p>{{form.description}}</p>
                        </div>
                        <div>
                            {{ form.payment_type}}
                        </div>
                        <button type="submit" class="site-btn col-lg-12">ثبت سفارش</button>
                    </div> 
                </form>              
                    <div class="col-lg-6 col-md-4">
                        <div class="checkout__order">
                            <h4>سفارش شما</h4>
                            <div class="checkout__order__products">کالاها <span>قیمت کل</span></div>
                            <ul>
                                {% for item in shop_cart  %}
                                <li>{{item.product}}<span>{{item.total_price}}</span></li>
                                {% endfor %}
                            </ul>
                            <div class="checkout__order__subtotal">جمع جز <span>{{total_price}}</span></div>
                            <div class="checkout__order__subtotal">مالیات <span>{{tax}}</span></div>
                            <div class="checkout__order__total">مبلغ قابل پرداخت <span>{{order_final_price}}</span></div>
                            <div class="checkout__input__checkbox">
                        </div>
                        <div class="col-lg-6">
                            <div class="shoping__continue">
                                <div class="shoping__discount">
                                    <h5>اعمال کد تخفیف</h5>
                                    <form action="{% url 'orders:apply_coupon' order_id=order.id %}" method="post">
                                        {% csrf_token %}
                                        {{coupon_form}}
                                        <button style="width:258px" type="submit" class="btn btn-primary" style="font-family:tahoma;font:tahoma">استفاده کد تخفیف</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/orders_app/shopcart.html
{% extends 'main_template.html' %} 
{% load render_partial %}

{% block title %}سبد خرید{% endblock title %}

{% block content %}
    <div id="shop_cart">
        {% render_partial 'orders:show_shop_cart' %}
    </div>
{% endblock content %}